//---------------------------------------------------------------
// Font generated by muGUI Font and Bitmap Generator (v.0.1.0.1), 
// available from http://www.muGUI.de
//
// Template for HiTech code, see http://edeca.net/wp/?p=874
//
// Project Name:  Verdana
//---------------------------------------------------------------

//---------------------------------------------------------------
// Group Name: Verdana8
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 11 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------

#ifndef _VERDANA_H_
#define _VERDANA_H_

extern const unsigned char Verdana8[];
extern const unsigned char Verdana22[];
extern const unsigned char Verdana16[];
extern const unsigned char Verdana32[];

#endif